Update to Docker and Webhook Workflows
eol-uchile/eol-edx pull request #395
Opened 2024-05-15 20:26 UTC by matiasua

**docker.yml**

- The workflow trigger has been updated to include the 'merge_group' action with the 'checks_requested' type, and the 'pull_request' action with the 'opened', 'reopened', and 'synchronize' types, restricted to the 'eol-release/koa' branch.
- Concurrency configuration has been added to manage jobs in specific groups, with the option to cancel jobs in progress if another is started in the same group.
- New environment variables have been introduced, and the logic for building Docker images has been modified to use these variables in the tag names and build targets.
- A condition has been added for the initiation of the login action to the GitHub Container Registry and the push action only on the 'merge_group' event.
- A webhook action has been added to execute after the preceding jobs are completed, only on the 'merge_group' event, which utilizes an external configuration file and inherits the necessary secrets.

**webhook.yml**
- The workflow trigger has been changed to include the 'workflow_call' event with a required 'code' input and the use of secrets.
- The 'if' condition in the 'build' job has been updated to evaluate the 'code' input and the 'client_payload.debug' field of the trigger event.
- The name of the step has been modified to better reflect its function.
- The execution script has been updated to include an 'if' condition that checks if the value of 'inputs.code' or 'github.event.client_payload.debug' is 'eol', and if so, it makes a POST request to the GitHub API to trigger an event in the 'edx-kustomize' repository.

2024-05-15 21:40 UTC, fsologureng requested changes

2024-05-15 21:40 UTC, fsologureng commented on .github/workflows/webhook.yml
> +            curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/
Agregar `--silent` please /|\

2024-05-15 21:40 UTC, fsologureng commented on .github/workflows/docker.yml
> +      PROJECT: ${{ needs.variables.outputs.project }}
Esta variable y la siguiente siempre son `eol`, así es que no es necesario usarlas desde `variables`. Sacarlas y ponerlas en duro donde se usaban.

2024-05-15 21:41 UTC, fsologureng commented on .github/workflows/webhook.yml
> +          if [[ "${{ inputs.code }}" = "eol" || "${{ github.event.client_payload.debug }}" = "eol" ]]
Este `if` es innecesario porque se testea en el if del job

2024-05-15 21:51 UTC, fsologureng commented on .github/workflows/docker.yml
> -    paths:
Este filtro era parte del evento `pull_request`

2024-05-15 21:56 UTC, matiasua commented on .github/workflows/webhook.yml
> +            curl --fail-with-body -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.github.com/
Done;

2024-05-15 21:56 UTC, matiasua commented on .github/workflows/docker.yml
> +      PROJECT: ${{ needs.variables.outputs.project }}
Done;

2024-05-15 21:56 UTC, matiasua commented on .github/workflows/webhook.yml
> +          if [[ "${{ inputs.code }}" = "eol" || "${{ github.event.client_payload.debug }}" = "eol" ]]
Done;

2024-05-15 22:20 UTC, fsologureng requested changes
Creo que es mejor sacar `eol` de todos los tags, porque el paquete ya es parte del proyecto eol, entonces queda redundante (a diferencia de staging que va a 2 proyectos distintos).

2024-05-15 22:20 UTC, fsologureng commented on .github/workflows/docker.yml
> +        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/eol-edx:eol-${{ env.RELEASE-NAME }} --tag ghcr.io/eol-uchile/eol-edx:s3-static-eol-${{ env.RELEASE-NAME }}-${{ env.TS }} --tar
Está mal puesto el tag del static

2024-05-15 22:20 UTC, fsologureng commented on .github/workflows/docker.yml
> +          docker push ghcr.io/eol-uchile/eol-edx:s3-static-${{ env.RELEASE-NAME }}-${{ env.TS }}
falta `eol` en este tag.

2024-05-15 22:20 UTC, fsologureng commented on .github/workflows/docker.yml
> +      with:
este parámetro sobra. No vamos a usar code.

2024-05-15 22:20 UTC, fsologureng commented on .github/workflows/webhook.yml
> +            curl --fail-with-body --silent -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.gi
quitar indentación agregada con el if que ya se quitó

2024-05-15 22:20 UTC, fsologureng commented on .github/workflows/webhook.yml
> +    inputs:
No se está usando este parámetro. Remover.

2024-05-16 00:27 UTC, matiasua commented on .github/workflows/docker.yml
> +          docker push ghcr.io/eol-uchile/eol-edx:s3-static-${{ env.RELEASE-NAME }}-${{ env.TS }}
Dado que vamos a eliminar "eol" del tag, ya que el paquete ya forma parte del proyecto eol, considero que este cambio no es necesario. Por el contrario, debo quitar "eol".

2024-05-16 00:27 UTC, matiasua commented on .github/workflows/docker.yml
> +        run: docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/eol-edx:eol-${{ env.RELEASE-NAME }} --tag ghcr.io/eol-uchile/eol-edx:s3-static-eol-${{ env.RELEASE-NAME }}-${{ env.TS }} --tar
Done;

2024-05-16 00:27 UTC, matiasua commented on .github/workflows/docker.yml
> +      with:
Done;

2024-05-16 00:28 UTC, matiasua commented on .github/workflows/webhook.yml
> +            curl --fail-with-body --silent -X POST -H "Authorization: Bearer ${{ secrets.WEBHOOK_SECRET }}" -H "Accept: application/vnd.github+json" -H "Content-Type: application/json" https://api.gi
Done;

2024-05-16 00:31 UTC, matiasua commented on .github/workflows/webhook.yml
> +    inputs:
done:

2024-05-16 13:46 UTC, fsologureng approved these changes

2024-05-16 15:14 UTC, fsologureng requested changes

2024-05-16 15:14 UTC, fsologureng commented on .github/workflows/webhook.yml
>    build:
Se olvidó cambiar el nombre de este step. Es confuso.

2024-05-16 15:15 UTC, fsologureng commented
>     * The workflow trigger has been changed to include the 'workflow_call' event with a required 'code' input and the use of secrets.
> 
>     * The 'if' condition in the 'build' job has been updated to evaluate the 'code' input and the 'client_payload.debug' field of the trigger event.

Outdated

>     * The name of the step has been modified to better reflect its function.
This was the name of the job. The step renaming is pending.

> 
>     * The execution script has been updated to include an 'if' condition that checks if the value of 'inputs.code' or 'github.event.client_payload.debug' is 'eol', and if so, it makes a POST request to the GitHub API to trigger an event in the 'edx-kustomize' repository.

Outdated

2024-05-16 16:42 UTC, matiasua commented on .github/workflows/webhook.yml
>    build:
done;

2024-05-16 17:33 UTC, merged